### ISSUE TITLE
unknown ssh parameter in docs

### ISSUE THREAD

**Issue by wafske** [ANA-Training/docs#6]
In README.md,line 100 "ssh -T git@github.com"
I didn't see "-T" parameter in the usage of ssh.What  does it for?
不常提issue，若英文不对还请指正^_^

**Comment by abdtyx** [comment]
Nothing crazy. I found this post which might be helpful: https://stackoverflow.com/questions/17900760/what-is-pseudo-tty-allocation-ssh-and-github
Because GitHub does not provide shell access, we just want to try whether GitHub can recognize us.
You can also try `ssh git@gitthub.com` without the `-T` arg.

**Comment by Dorbmon** [comment]
So have you solved the problem?

**Comment by wafske** [comment]
> Nothing crazy. I found this post which might be helpful: https://stackoverflow.com/questions/17900760/what-is-pseudo-tty-allocation-ssh-and-github Because GitHub does not provide shell access, we just want to try whether GitHub can recognize us. You can also try `ssh git@gitthub.com` without the `-T` arg.

Understood,thank u

**Comment by wafske** [comment]
> So have you solved the problem?

I just had some trouble understanding that `-T` arg,you can see the reply above.
